---

- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master
  become: true
  roles:
    - role: k3s/master

- hosts: node
  become: true
  roles:
    - role: k3s/node

- hosts: master[0]
  become: true
  roles:
    - role: helm

- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: reboot

- hosts: master[0]
  roles:
    - role: cert-manager

- hosts: master[0]
  roles:
    - role: traefik