---
#k3s_version: v1.24.3+k3s1
k3s_version: v1.23.9+k3s1
# this is the user that has ssh access to these machines
ansible_user: ansibleuser
systemd_dir: /etc/systemd/system

# Set your environment
deployment_environment: staging
#deployment_environment: production

# Set your timezone
system_timezone: "Your/Timezone"

# interface which will be used for flannel
flannel_iface: "eth0"

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: "192.168.30.222"

# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
k3s_token: "some-SUPER-DEDEUPER-secret-password"

# change these to your liking, the only required one is --disable servicelb
extra_server_args: "--disable servicelb --disable traefik"
extra_agent_args: ""

# image tag for kube-vip
kube_vip_tag_version: "v0.5.0"

# image tag for metal lb
metal_lb_speaker_tag_version: "v0.13.4"
metal_lb_controller_tag_version: "v0.13.4"

# metallb ip range for load balancer
metal_lb_ip_range: "192.168.30.80-192.168.30.90"

# first ip from metallb range for internal traefik
traefik_internal_endpoint_ip: "192.168.30.80"
traefik_internal_dash_dns_name: "traefik.local.example.com"

# second ip from metallb range for external traefik
traefik_external_endpoint_ip: "192.168.30.81"
traefik_external_dash_dns_name: "traefik.example.com"

# external dashboard user
traefik_dashboard_secret: "dGVjaG5vOiRhcHIxJFRnVVJ0N2E1JFpoTFFGeDRLMk8uYVNaVWNueG41eTAKCg=="

# cloudflare api key
cloudflare_email: "user@example.com"
cloudflare_token: "some-SUPER-DEDEUPER-secret-token"

# image tag for cert-manager
cert_manager_version: "v1.9.1"

# cert manager domains
cert_manager_internal_domain: "local.example.com"
cert_manager_external_domain: "example.com"